### ISSUE TITLE
WWS list / fetch fails on fresh install

### ISSUE THREAD

**Issue by nickisnoble** [breck7/scroll#115]
Maybe I've missed something, but following the instructions in wws.scroll, this is what I get on `wws list` or `wws fetch`

```
Error reading '$path'
/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/Disk.node.js:16
    throw err
    ^

Error: ENOENT: no such file or directory, open '/opt/homebrew/lib/node_modules/scroll-cli/header.scroll'
```

**Comment by breck7** [comment]
Can you share a full screenshot? Here's what I get

![Screenshot 2024-06-29 at 5 47 40 AM](https://github.com/breck7/scroll/assets/74692/99f449c8-4a26-4780-8acf-794cb2c07046)

**Comment by nickisnoble** [comment]
### Output:


```sh
❯ npm i -g scroll-cli
added 8 packages in 246ms

1 package is looking for funding
  run `npm fund` for details

❯ wws init
👍 Initialized new WWS cache in '/Users/nn/Code/wws'.

❯ wws fetch
Error reading '$path'
/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/Disk.node.js:16
    throw err
    ^

Error: ENOENT: no such file or directory, open '/opt/homebrew/lib/node_modules/scroll-cli/header.scroll'
    at Object.readFileSync (node:fs:448:20)
    at Disk.read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/Disk.node.js:13:15)
    at DiskWriter._read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:20:91)
    at DiskWriter.read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:24:17)
    at ScrollFileSystem.read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:77:26)
    at ScrollFileSystem._assembleFile (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:104:21)
    at /opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:132:35
    at Array.forEach (<anonymous>)
    at ScrollFileSystem._assembleFile (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:127:11)
    at ScrollFileSystem.assembleFile (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:196:32) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/homebrew/lib/node_modules/scroll-cli/header.scroll'
}

Node.js v22.3.0

❯ wws list
Error reading '$path'
/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/Disk.node.js:16
    throw err
    ^

Error: ENOENT: no such file or directory, open '/opt/homebrew/lib/node_modules/scroll-cli/header.scroll'
    at Object.readFileSync (node:fs:448:20)
    at Disk.read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/Disk.node.js:13:15)
    at DiskWriter._read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:20:91)
    at DiskWriter.read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:24:17)
    at ScrollFileSystem.read (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:77:26)
    at ScrollFileSystem._assembleFile (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:104:21)
    at /opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:132:35
    at Array.forEach (<anonymous>)
    at ScrollFileSystem._assembleFile (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:127:11)
    at ScrollFileSystem.assembleFile (/opt/homebrew/lib/node_modules/scroll-cli/node_modules/scrollsdk/products/TreeFileSystem.js:196:32) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/homebrew/lib/node_modules/scroll-cli/header.scroll'
}

Node.js v22.3.0
```

If I `$ ls -al /opt/homebrew/lib/node_modules/scroll-cli/` to check, everything is there but not `header.scroll`
```sh
❯ ls -al /opt/homebrew/lib/node_modules/scroll-cli/
total 192
drwxr-xr-x@ 11 nn  admin    352 Jun 29 11:46 .
drwxr-xr-x@ 14 nn  admin    448 Jun 29 11:46 ..
drwxr-xr-x@ 15 nn  admin    480 Jun 29 11:46 external
drwxr-xr-x@ 10 nn  admin    320 Jun 29 11:46 node_modules
-rw-r--r--@  1 nn  admin   1386 Jun 29 11:46 package.json
drwxr-xr-x@ 75 nn  admin   2400 Jun 29 11:46 parsers
-rw-r--r--@  1 nn  admin  34265 Jun 29 11:46 readme.html
-rw-r--r--@  1 nn  admin   2586 Jun 29 11:46 readme.scroll
-rwxr-xr-x@  1 nn  admin  38002 Jun 29 11:46 scroll.js
-rwxr-xr-x@  1 nn  admin   5447 Jun 29 11:46 wws.js
-rw-r--r--@  1 nn  admin   4006 Jun 29 11:46 wws.scroll
```

And the `wws` folder created with `wws init` just has index.scroll containing `The World Wide Scroll`

**Comment by nickisnoble** [comment]
Also tried upgrading homebrew, node, npm, and reinstalling

**Comment by breck7** [comment]
Fantastic bug report. Just pushed a fix (hopefully). Thanks @nickisnoble !

**Comment by nickisnoble** [comment]
Still having an issue after fresh install, this time:
```
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/homebrew/lib/node_modules/scroll-cli/stripeBuyButton.scroll'
```

**Comment by breck7** [comment]
Sorry! Just added that file to the npm package.

I've got to add some automated tests for `wws` to run in CI to pick up things like this.

**Comment by breck7** [comment]
Okay I'm going to move WWS to its own repo with its own tests

**Comment by breck7** [comment]
It will be here:
https://github.com/breck7/wws

**Comment by breck7** [comment]
Okay @nickisnoble . Version 0.4.0 is live and with a better design. Install directly from GitHub now:

```
 git clone https://github.com/breck7/wws
 cd wws
 npm install -g .
 wws list
 wws fetch scroll
 wws open
```
